### ISSUE TITLE
Implement Prototype

### ISSUE THREAD

**Issue by tahic-himzo** [tahic-himzo/scala-yaml#1]
# Task 1: Implement Protoype
Interface:
`parse(input: Seq[String]): Either[ParseError, Yaml]`
`decode[T](yaml: Yaml): Either[DecodeError, T]`

# 1.1 Bootstrap Library
- [ ] Setup all the bootstrapping needed to publish the library locally.
- [ ] Export a library that exposes the above method and returns `Left(MalformedInputError)`

# 1.2 Implement YAML AST
- [ ] Scalar
  - [ ] Integer
  - [ ] String
  - [ ] Float/Double
  - [ ] Boolean
- [ ] Sequences
- [ ] Mappings
- [ ] YAML

# 1.3 Implement Parser Typeclasses for Scala Basic Types
- [ ] Integer
- [ ] String
- [ ] Double
- [ ] Boolean
- [ ] List
- [ ] Map

# 1.4 Implement parse & decode method from above using the created typeclasses
- [ ] Do it

# 1.5 Create syntax methods
- [ ] Make parse & decode available as syntax
